site_name: Torn API Python Package Documentation
site_description: Documentation for the Torn API Python client wrapper.
site_author: Dustin Spencer

theme:
  name: material

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - API Reference: api_reference.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
